export const ROLES = {
  ADMIN: "ADMIN",
  SELLER: "SELLER",
  BUYER: "BUYER",
  DRIVER: "DRIVER",
};

export const ORDER_STATUS = {
  PACKING: "PACKING",
  WAITING_DELIVERY: "WAITING_DELIVERY",
  DELIVERING: "DELIVERING",
  COMPLETED: "COMPLETED",
  RETURNED: "RETURNED",
};

export const DELIVERY_METHOD = {
  INSTANT: "INSTANT",
  NEXT_DAY: "NEXT_DAY",
  REGULAR: "REGULAR",
};

export const DELIVERY_JOB_STATUS = {
  AVAILABLE: "AVAILABLE",
  TAKEN: "TAKEN",
  COMPLETED: "COMPLETED",
};

export const DISCOUNT_TYPE = {
  PERCENTAGE: "PERCENTAGE",
  FIXED: "FIXED",
};

export const WALLET_TX_TYPE = {
  TOPUP: "TOPUP",
  PAYMENT: "PAYMENT",
  REFUND: "REFUND",
  EARNING: "EARNING",
};
